CREATE DATABASE IF NOT EXISTS E2E_DB;
USE DATABASE E2E_DB;
CREATE SCHEMA IF NOT EXISTS RAW;


CREATE OR REPLACE FILE FORMAT E2E_DB.RAW.E2E_PARQUET_FORMAT
  TYPE = 'PARQUET'
  COMPRESSION = 'SNAPPY';
CREATE OR REPLACE STAGE E2E_DB.RAW.E2E_S3_STAGE
  URL = 's3://e2e-datalake-20251124132222620400000001/bank_data/'
  STORAGE_INTEGRATION = E2E_S3_INTEGRATION 
  FILE_FORMAT = E2E_DB.RAW.E2E_PARQUET_FORMAT;
  
-- ========= BẢNG CUSTOMERS =========

-- Bảng thô (RAW) để Snowpipe nạp vào
CREATE OR REPLACE TABLE E2E_DB.RAW.CUSTOMERS_LANDING (
  PAYLOAD VARIANT,
  LOAD_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

---

-- ========= BẢNG ACCOUNTS =========

CREATE OR REPLACE TABLE E2E_DB.RAW.ACCOUNTS_LANDING (
  PAYLOAD VARIANT,
  LOAD_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);


---

-- ========= BẢNG TRANSACTIONS =========

CREATE OR REPLACE TABLE E2E_DB.RAW.TRANSACTIONS_LANDING (
  PAYLOAD VARIANT,
  LOAD_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);






-- 1. Pipe cho CUSTOMERS
CREATE OR REPLACE PIPE E2E_DB.RAW.PIPE_CUSTOMERS
  AUTO_INGEST = TRUE -- Bật chế độ tự động
AS
COPY INTO E2E_DB.RAW.CUSTOMERS_LANDING (PAYLOAD)
FROM (
  SELECT $1 -- $1 nghĩa là toàn bộ nội dung file Parquet
  FROM @E2E_DB.RAW.E2E_S3_STAGE/customers/ -- Chỉ đọc thư mục customers
);

-- 2. Pipe cho ACCOUNTS
CREATE OR REPLACE PIPE E2E_DB.RAW.PIPE_ACCOUNTS
  AUTO_INGEST = TRUE
AS
COPY INTO E2E_DB.RAW.ACCOUNTS_LANDING (PAYLOAD)
FROM (
  SELECT $1
  FROM @E2E_DB.RAW.E2E_S3_STAGE/accounts/ -- Chỉ đọc thư mục accounts
);

-- 3. Pipe cho TRANSACTIONS
CREATE OR REPLACE PIPE E2E_DB.RAW.PIPE_TRANSACTIONS
  AUTO_INGEST = TRUE
AS
COPY INTO E2E_DB.RAW.TRANSACTIONS_LANDING (PAYLOAD)
FROM (
  SELECT $1
  FROM @E2E_DB.RAW.E2E_S3_STAGE/transactions/ -- Chỉ đọc thư mục transactions
);